#lang plai/gc2/mutator
(allocator-setup "gc.rkt" 200)
(define (build-one)
  (let* ((x0 1)
         (x1 'x)
         (x2 -1)
         (x3 (lambda (x) (if (= x 0) x1 (if (= x 1) x2 (if (= x 2) x2 x0)))))
         (x4 #f)
         (x5 (cons x0 x4)))
    x3))
(define (traverse-one x3) (= -1 (x3 1)))
(define (trigger-gc n)
  (if (zero? n) 0 (begin (cons n n) (trigger-gc (- n 1)))))
(define (loop i)
  (if (zero? i)
    'passed
    (let ((obj (build-one)))
      (trigger-gc 200)
      (if (traverse-one obj) (loop (- i 1)) 'failed))))
(loop 200)
